<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>Search category</h1>
    <p><?php echo $this->tag->linkTo(["category/new", "Create category"]) ?></p>
</div>

<?php echo $this->getContent() ?>

<form action="category/search" class="form-horizontal" method="get">
    <div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCategoryName" class="col-sm-2 control-label">Category Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["category_name", "size" => 30, "class" => "form-control", "id" => "fieldCategoryName"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
