<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["tdetails", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Edit tdetails</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="tdetails/save" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldTransaction" class="col-sm-2 control-label">Transaction</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["transaction", "type" => "number", "class" => "form-control", "id" => "fieldTransaction"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCategory" class="col-sm-2 control-label">Category</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["category", "type" => "number", "class" => "form-control", "id" => "fieldCategory"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAmount" class="col-sm-2 control-label">Amount</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["amount", "type" => "number", "class" => "form-control", "id" => "fieldAmount"]) ?>
    </div>
</div>


    <?php echo $this->tag->hiddenField("id") ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
