<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>Search tdetails</h1>
    <p><?php echo $this->tag->linkTo(["tdetails/new", "Create tdetails"]) ?></p>
</div>

<?php echo $this->getContent() ?>

<form action="tdetails/search" class="form-horizontal" method="get">
    <div class="form-group">
    <label for="fieldTransaction" class="col-sm-2 control-label">Transaction</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["transaction", "type" => "number", "class" => "form-control", "id" => "fieldTransaction"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCategory" class="col-sm-2 control-label">Category</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["category", "type" => "number", "class" => "form-control", "id" => "fieldCategory"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAmount" class="col-sm-2 control-label">Amount</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["amount", "type" => "number", "class" => "form-control", "id" => "fieldAmount"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
